### ISSUE TITLE
Denoising Encoder

### ISSUE THREAD

**Issue by Mrforeman1** [Stream-AD/MemStream#2]
The encoder used in the implementation is difference than in the paper.  The paper mentioned using a neural network with relu activation.  I don't see that anywhere in the code.

**Comment by Mrforeman1** [comment]
Disregard

**Comment by zhoup150344** [comment]
Hello, could you please tell me the 'nsllabel.txt' in the lfile = '../data/nsllabel.txt', Is it directly obtained from the NSL-KDD dataset?

**Comment by bhatiasiddharth** [comment]
You can use any activation function for the encoder-decoder architecture. In the updated implementation, we're using the tanh activation function. The proof in Section 4.5.2 of the paper (Architecture Choice) and Proposition 2, works with functions whose transformations can be thought of as an application of a diagonal matrix with 0s and 1s, like ReLU or Max Pooling.
