### ISSUE TITLE
Dataset of problem

### ISSUE THREAD

**Issue by zhoup150344** [Stream-AD/MemStream#3]
Hello, could you please tell me the 'nsllabel.txt' in the lfile = '../data/nsllabel.txt', Is it directly obtained from the NSL-KDD dataset?

**Comment by bhatiasiddharth** [comment]
@zhoup150344: Yes, the labels are directly obtained from the NSL-KDD dataset.

**Comment by zhoup150344** [comment]
Thank you for your reply!I still have some questions, may I ask if you directly use the original data set of NSL-kDD? I delete the non-numerical data in the data set during operation, so that the code can run!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Stream-AD/MemStream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月18日(星期四) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Stream-AD/MemStream] Dataset of problem (Issue #3)





 
@zhoup150344: Yes, the labels are directly obtained from the NSL-KDD dataset.

**Comment by bhatiasiddharth** [comment]
Yes, we use the original data set of NSL-KDD. We used one-hot encoding for categorical features.
